AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GitHubRepo:
    Description: Name of the GitHub repo
    Type: String
    Default: marc-projects/lazgar

Resources:
  DeploymentBucket: 
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${AWS::StackName}-web
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  
  # dont know how to tweak the name
  DeploymentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: DeploymentBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DeploymentBucket
                - /*
      Bucket: !Ref DeploymentBucket

