AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a static website using S3

# input parameters of the template
Parameters:
  WebsiteBucketName:
    Type: String
    Description: The name for the bucket hosting your website
    Default: lazgar

Resources:
  # web site
  Bucket:
    Type: "AWS::S3::Bucket"
    Description: S3 bucket containing the Web site content
    Properties:
      BucketName: !Ref WebsiteBucketName
      WebsiteConfiguration:
        IndexDocument: index.html

  # public access
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Description: Access policy for the Web site bucket
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${Bucket}/*"
  
Outputs:
  websiteURL:
    Value: !GetAtt Bucket.WebsiteURL
